CREATE DATABASE Contacts
GO

USE Contacts
GO

CREATE TABLE Contacts(
	ID INT IDENTITY PRIMARY KEY,
	Nom VARCHAR(25) NOT NULL ,
	Prenom VARCHAR(25) NOT NULL,
	TEL INT NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	

)